spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: cliente
          uri: lb://cliente
          predicates:
            - Path=/api/cliente/**
        - id: profesional
          uri: lb://profesional
          predicates:
            - Path=/api/profesional/**
        - id: tipoServicio
          uri: lb://tipoServicio
          predicates:
            - Path=/api/tipoServicio/**,/api/tiposervicio/**
          filters:
            - RewritePath=/api/tipoServicio(?<segment>/?.*), /api/tiposervicio$\{segment}
        - id: disponibilidad
          uri: lb://disponibilidadProfesional
          predicates:
            - Path=/api/disponibilidad/**
        - id: agenda
          uri: lb://agenda
          predicates:
            - Path=/api/agenda/**

        - id: cliente-docs
          uri: lb://cliente
          predicates:
            - Path=/cliente/v3/api-docs
          filters:
            - RewritePath=/cliente/(?<segment>.*), /$\{segment}
        - id: profesional-docs
          uri: lb://profesional
          predicates:
            - Path=/profesional/v3/api-docs
          filters:
            - RewritePath=/profesional/(?<segment>.*), /$\{segment}
        - id: tipoServicio-docs
          uri: lb://tipoServicio
          predicates:
            - Path=/tipoServicio/v3/api-docs
          filters:
            - RewritePath=/tipoServicio/(?<segment>.*), /$\{segment}
        - id: disponibilidadProfesional-docs
          uri: lb://disponibilidadProfesional
          predicates:
            - Path=/disponibilidadProfesional/v3/api-docs
          filters:
            - RewritePath=/disponibilidadProfesional/(?<segment>.*), /$\{segment}
        - id: agenda-docs
          uri: lb://agenda
          predicates:
            - Path=/agenda/v3/api-docs
          filters:
            - RewritePath=/agenda/(?<segment>.*), /$\{segment}

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Cliente
        url: /cliente/v3/api-docs
      - name: Profesional
        url: /profesional/v3/api-docs
      - name: Tipo de Servicio
        url: /tipoServicio/v3/api-docs
      - name: Disponibilidad Profesional
        url: /disponibilidadProfesional/v3/api-docs
      - name: Agenda
        url: /agenda/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info